<?php

/**
 * @file
 * Contains UC Tejarat Payment required hook implementations and callbacks.
 */

/**
 * Defines API version.
 */
define('UC_TEJARAT_API_VERSION', '3.1');

/**
 * Defines gateway default controller URI.
 */
define('UC_TEJARAT_GATEWAY_URI', 'https://pg.tejaratbank.net/paymentGateway/page');

/**
 * Defines gateway default SOAP Server URI.
 */
define('UC_TEJARAT_SOAP_URI', 'http://pg.tejaratbank.net/paymentGateway/services/merchant.wsdl');

/**
 * Defines test gateway default controller URI.
 */
define('UC_TEJARAT_TEST_GATEWAY_URI', 'http://pg.sabapardazesh.net:9085/paymentGateway/page');

/**
 * Defines test gateway default SOAP Server URI.
 */
define('UC_TEJARAT_TEST_SOAP_URI', 'http://pg.sabapardazesh.net:9086/paymentGateway/services/merchant.wsdl');

/**
 * Implements hook_menu().
 */
function uc_tejarat_menu() {
  $items = array();

  $items['cart/tejarat/complete'] = array(
    'title' => 'Order payment status',
    'page callback' => 'uc_tejarat_complete',
    'access callback' => 'uc_tejarat_access',
    'file' => 'uc_tejarat.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_payment_method().
 */
function uc_tejarat_payment_method() {
  $methods = array();

  $methods[] = array(
    'id' => 'tejarat',
    'name'  => t('Tejarat Bank'),
    'title' => t('Tejarat Bank'),
    'desc'  => t('Redirect to Tejarat bank payment gateway.'),
    'callback' => 'uc_tejarat_settings',
    'weight' => 1,
    'checkout' => TRUE,
    'no_gateway' => TRUE,
  );

  return $methods;
}

/**
 * Implements hook_ucga_display().
 *
 * @see http://api.ubercart.org/api/function/hook_ucga_display/2
 */
function uc_tejarat_ucga_display() {
  if (implode('/', arg()) == 'cart/tejarat/complete') {
    return TRUE;
  }
}

/**
 * Implements hook_form_alter() for uc_cart_checkout_review_form.
 *
 * Alters the order review form and injects required hidden fields,
 * also alteres its action attribute, addressing the Tejarat Bank gateway.
 */
function uc_tejarat_form_uc_cart_checkout_review_form_alter(&$form, $form_state) {
  $order_id = intval($_SESSION['cart_order']);
  // Check order identifier.
  if ($order_id > 0 && ($order = uc_order_load($order_id))) {
    // Alter the form if it's a Tejarat Bank payment.
    if ($order->payment_method == 'tejarat') {
      // Prepare the order object in form of Tejarat compatible data.
      if ($data = _uc_tejarat_prepare($order)) {
        // Inject hidden fields.
        _uc_tejarat_hidden_fields($data, $form);
        // And update the form action.
        $form['#action'] = _uc_tejarat_gateway_uri('controller');
      }
      // Problems!
      else {
        // Notify customer.
        drupal_set_message(t('There were a problem preparing your order for Tejarat Bank payment. If possible, choose another payment method or try again later.'), 'error');
        // Notify the dog!
        watchdog(
          'uc_tejarat',
          'There were a problem preparing the order ID %order for Tejarat Bank payment.',
          array('%order' => $order->order_id),
          WATCHDOG_ERROR
        );
        // And return to checkout page.
        drupal_goto('cart/checkout');
      }
    }
  }
}

/**
 * Implements hook_form_alter() for uc_payment_methods_form.
 *
 * Attaches an aditional form validation callback, so we can validate
 * Tejarat Bank's configuration settings.
 *
 * @see uc_tejarat_settings_validate()
 */
function uc_tejarat_form_uc_payment_methods_form_alter(&$form, $form_state) {
  $form['#validate'][] = 'uc_tejarat_settings_validate';
}

/**
 * Form callback for Ubercart Tejarat Bank Payment settings.
 */
function uc_tejarat_settings($op, &$arg1) {
  if ($op == 'settings') {
    $form = array();

    // Merchant code:
    $form['uc_tejarat_merchant_code'] = array(
      '#type' => 'textfield',
      '#title' => t('Merchant code'),
      '#description' => t('Enter the merchant code provided by Tejarat Bank.'),
      '#default_value' => variable_get('uc_tejarat_merchant_code', ''),
      '#required' => TRUE,
    );
    // Merchant password:
    $form['uc_tejarat_merchant_password'] = array(
      '#type' => 'textfield',
      '#title' => t('Merchant password'),
      '#description' => t('Enter the merchant password provided by Tejarat Bank.'),
      '#default_value' => variable_get('uc_tejarat_merchant_password', ''),
      '#required' => TRUE,
    );

    // Gateway URI settings:
    $form['additional'] = array(
      '#type' => 'fieldset',
      '#title' => t('Additional options'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );
    // Tejarat Bank gateway address:
    $form['additional']['uc_tejarat_gateway_uri'] = array(
      '#type' => 'textfield',
      '#title' => t('Tejarat gateway URI'),
      '#description' => t('Do not change the default value unless you checked the Tejarat bank docs and it has changed.'),
      '#default_value' => variable_get('uc_tejarat_gateway_uri', UC_TEJARAT_GATEWAY_URI),
      '#required' => TRUE,
    );
    // Tejarat Bank SOAP endpoint address:
    $form['additional']['uc_tejarat_soap_uri'] = array(
      '#type' => 'textfield',
      '#title' => t('Tejarat SOAP Server URI'),
      '#description' => t('Do not change the default value unless you checked the Tejarat bank docs and it has changed.'),
      '#default_value' => variable_get('uc_tejarat_soap_uri', UC_TEJARAT_SOAP_URI),
      '#required' => TRUE,
    );

    // Test Gateway URI settings:
    $form['additional']['test'] = array(
      '#type' => 'fieldset',
      '#title' => t('Test gateway'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );
    // Use the test gateway?
    $form['additional']['test']['uc_tejarat_test_env'] = array(
      '#type' => 'checkbox',
      '#title' => t('Operate in test environment'),
      '#description' => t('If checked, the system will operate in an test environment and so there will be no actual payment. Make sure to disable this feature in production.'),
      '#default_value' => variable_get('uc_tejarat_test_env', 0),
      '#return_value'  => 1,
    );
    // Tejarat Bank gateway address:
    $form['additional']['test']['uc_tejarat_test_gateway_uri'] = array(
      '#type' => 'textfield',
      '#title' => t('Tejarat test gateway URI'),
      '#description' => t('Will be used as the gateway controller URI if operating in test environment.'),
      '#default_value' => variable_get('uc_tejarat_test_gateway_uri', UC_TEJARAT_TEST_GATEWAY_URI),
    );
    // Tejarat Bank SOAP endpoint address:
    $form['additional']['test']['uc_tejarat_test_soap_uri'] = array(
      '#type' => 'textfield',
      '#title' => t('Tejarat test SOAP Server URI'),
      '#description' => t('Will be used as the gateway SOAP server endpoint if operating in test environment.'),
      '#default_value' => variable_get('uc_tejarat_test_soap_uri', UC_TEJARAT_TEST_SOAP_URI),
    );

    return $form;
  }
}

/**
 * Form validation callback for settings form.
 */
function uc_tejarat_settings_validate($form, &$form_state) {
  // Check gateway controller URL.
  if (!valid_url($form_state['values']['uc_tejarat_gateway_uri'], TRUE)) {
    form_set_error('uc_tejarat_gateway_uri', t('Tejarat bank gateway URI must be valid.'));
  }
  // Check SOAP Server URL.
  if (!valid_url($form_state['values']['uc_tejarat_soap_uri'], TRUE)) {
    form_set_error('uc_tejarat_soap_uri', t('Tejarat bank SOAP server URI must be valid.'));
  }
  // Check test gateway controller URL, if set.
  if (!empty($form_state['values']['uc_tejarat_test_gateway_uri']) &&
      !valid_url($form_state['values']['uc_tejarat_test_gateway_uri'], TRUE)) {
    form_set_error('uc_tejarat_gateway_uri', t('Tejarat bank test gateway URI must be valid.'));
  }
  // Check test SOAP Server URL, if set.
  if (!empty($form_state['values']['uc_tejarat_test_soap_uri']) &&
      !valid_url($form_state['values']['uc_tejarat_test_soap_uri'], TRUE)) {
    form_set_error('uc_tejarat_soap_uri', t('Tejarat bank test SOAP server URI must be valid.'));
  }
}

/**
 * Menu routes access callback.
 *
 * Ensures a free access to defined menu paths.
 */
function uc_tejarat_access() {
  return TRUE;
}

/**
 * Internal helper that builds Tejarat compatible data out of an UC order object.
 *
 * @param $order
 *   Ubercart order object.
 *
 * @return
 *   Either an array representation of data as per required by
 *   Tejarat Bank gateway or FALSE on operation failure.
 */
function _uc_tejarat_prepare($order) {
  // Partially check requirements.
  if (!is_object($order) || !variable_get('uc_tejarat_merchant_code', FALSE)) {
    return FALSE;
  }

  global $base_root;
  // Build and return the data array out of the $order.
  return array(
    'customerId' => $order->uid,
    'paymentId'  => $order->order_id,
    'amount' => round($order->order_total),
    'revertURL'  => $base_root . url('cart/tejarat'),
    'merchantId' => variable_get('uc_tejarat_merchant_code', ''),
  );
}

/**
 * Internal helper that injects required hidden fields to the passed form array.
 *
 * @param $data
 *   Array representation of required data.
 * @param $form
 *   Form (sub)array.
 *
 * @return
 *   Field injected form (sub)array.
 */
function _uc_tejarat_hidden_fields($data, &$form = array()) {
  foreach ($data as $key => $value) {
    $form[$key] = array(
      '#type' => 'hidden',
      '#value' => $value,
    );
  }
}

/**
 * Internal helper that returns proper controller/SOAP URI based on the environment.
 *
 * @param $type
 *   URI type to return:
 *   - both
 *   - soap
 *   - controller
 *
 * @param $test_env
 *   Boolean that indicates if we're operating in test environment.
 *
 * @return
 *   The proper gateway URI.
 */
function _uc_tejarat_gateway_uri($type = 'both', $test_env = NULL) {
  // Check environment.
  $test_env = is_null($test_env) ?
    variable_get('uc_tejarat_test_env', FALSE) :
    (bool) $test_env;

  // Get proper URIs.
  $uris = array(
    // SOAP server URI:
    'soap' => $test_env ?
      variable_get('uc_tejarat_test_soap_uri', UC_TEJARAT_TEST_SOAP_URI) :
      variable_get('uc_tejarat_soap_uri', UC_TEJARAT_SOAP_URI),
    // Controller URI:
    'controller' => $test_env ?
      variable_get('uc_tejarat_test_gateway_uri', UC_TEJARAT_TEST_GATEWAY_URI) :
      variable_get('uc_tejarat_gateway_uri', UC_TEJARAT_GATEWAY_URI),
  );

  // Return desired output.
  return $type == 'both' ? $uris : $uris[$type];
}
